services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    command: ["uvicorn", "plantguard.src.backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend